---
name: 🔬 PR Analysis

on:
  pull_request:

jobs:
  pr-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ingka-group-digital/ocp-pipelines/composites/go-pr@v2.7.0
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
