name: 🔬 PR Analysis

on:
  pull_request:

permissions:
  pull-requests: read
  contents: read
  id-token: write

jobs:
  pr-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Triage PR title
        if: ${{ startsWith(github.head_ref, 'dependabot/') != true }}
        uses: amannn/action-semantic-pull-request@v5.5.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check out source code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: Setup deps
        shell: bash
        run: |
          # A linter that helps with getting the import ordering right
          go install github.com/hedhyw/go-import-lint/cmd/go-import-lint@latest

          # A state-of-the-art golang linter.
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run .pre-commit-config.yaml
        uses: pre-commit/action@v3.0.0

      - name: JFrog scanning
        uses: ingka-group/echoprobe/.github/composites/jfrog@fix/jfrog
        with:
          jf_url: ${{ secrets.JF_URL }}
          jf_oidc_provider: ${{ secrets.JF_OIDC_PROVIDER }}
          jf_oidc_audience: ${{ secrets.JF_OIDC_AUDIENCE }}
          jf_repo: ${{ secrets.JF_GO_DEV_REPO }}
          version: ${{ steps.bump_version.outputs.new_tag }}
