name: 🔬 PR Analysis

on:
  pull_request:

jobs:
  pr-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ingka-group-digital/ocp-pipelines/.github/actions/pre-commit@main
