---
name: 🔖 Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: ingka-group-digital/ocp-pipelines/actions/git-private@v2.2.4
        with:
          gh_bot_token: ${{ secrets.GH_BOT_TOKEN }}

      - name: Run SonarQube scanner
        uses: ingka-group-digital/ocp-pipelines/actions/golang-sonarqube@v2.2.4
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Get latest tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
        id: previous_version
        with:
          prefix: v

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0
        id: bump_version
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
          RELEASE_BRANCHES: main
          # custom tagging policy adapted to conventional commits
          MAJOR_STRING_TOKEN: feat!
          MINOR_STRING_TOKEN: feat
          DEFAULT_BUMP: patch

      - name: Create GitHub release
        uses: ingka-group-digital/ocp-pipelines/composites/create-release@v2.2.4
        with:
          latest_release_tag: ${{ steps.previous_version.outputs.tag }}
          new_release_tag: ${{ steps.bump_version.outputs.new_tag }}
