name: version

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: version
          DEFAULT_BUMP: patch
