name: 🔖 Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: ingka-group-digital/ocp-pipelines/actions/git-private@v1.15.0
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}

      - name: Run SonarQube scanner
        uses: ingka-group-digital/ocp-pipelines/actions/golang-sonarqube@v1.15.0
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: minor
