name: 🔖 Versioning

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: version
          DEFAULT_BUMP: patch
